######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 23 14:54:18 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += OthelloBoard.h OthelloItem.h
SOURCES += main.cpp OthelloBoard.cpp OthelloItem.cpp
