######################################################################
# Automatically generated by qmake (2.01a) Sun Mar 14 12:03:18 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += OthelloBoard.h OthelloItem.h
SOURCES += main.cpp OthelloBoard.cpp OthelloItem.cpp
