######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 19 16:11:17 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += OthelloBoard.h OthelloItem.h OthelloFunctions.cpp
SOURCES += main.cpp OthelloBoard.cpp OthelloFunctions.cpp OthelloItem.cpp
