######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 3 23:27:32 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += OthelloBoard.h OthelloItem.h
SOURCES += main.cpp OthelloBoard.cpp OthelloItem.cpp
