######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 19 15:07:16 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Othelloboard.h OthelloItem.h
SOURCES += main.cpp Othelloboard.cpp OthelloItem.cpp
