######################################################################
# Automatically generated by qmake (2.01a) ?????? ???? 8 13:37:14 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
