######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 26 01:05:57 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += OthelloBoard.h OthelloItem.h
SOURCES += main.cpp OthelloBoard.cpp OthelloItem.cpp
