######################################################################
# Automatically generated by qmake (2.01a) ?????? ???? 8 19:33:28 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += qt console

# Input
SOURCES += console.cpp
